networks:
  web:
    name: web
  intercom:
    name: intercom

volumes:
  order_pg_vol:
  sws_pg_vol:

services:
  traefik:
    image: "traefik:v3.5.2"
    container_name: "traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - web
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=web"
      - "--entryPoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"
      - "8080:8080"
    # todo add traefik config
    # todo only expose network web



  orderservice:
    container_name: orderservice
    build: .
    restart: unless-stopped
    command: [ "/app/ordersystem" ]
    depends_on:
      order-postgres:
        condition: service_healthy
    # todo add traefik labels
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orderservice.rule=Host(`orders.localhost`)"
      - "traefik.http.routers.orderservice.entrypoints=web"
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_TCP_PORT=5432
      - DB_HOST=order-postgres
    networks:
      - intercom
      - web

  sws:
    image: joseluisq/static-web-server:latest
    container_name: "sws"
    restart: unless-stopped
    networks:
      - web
    environment:
      - SERVER_ROOT=/public                
      - SERVER_PORT=80 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sws.rule=Host(`localhost`)"
      - "traefik.http.routers.sws.entrypoints=web"
    ports: 
      - 100:80
    volumes:
      - type: bind
        source: ./frontend
        target: /app/fronten
      
      #- sws_pg_vol:/mnt/host/c/Users/maria/documents/3rd Semester/sabd/exercise/SBD-AIS-Exercise/SBD-AIS-Exercise/Exc_5/skeleton/frontend


    # todo add frontend folder as volume
    # todo setup environment variables to expose port 80 and serve the frontend folder
    # todo add traefik labels

  order-postgres:
    image: postgres:latest
    restart: always
    networks:
      - intercom
    volumes:
      - order_pg_vol:/var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_TCP_PORT=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d order -U docker"]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s